### ISSUE TITLE
Пауза ставится везде, даже где не нужно

### ISSUE THREAD

**Issue by m65v19** [oneza/RG#10]
Пауза ставится везде, даже где не нужно, а в rm_start, rm_death после отключения меню все отрисовывается криво - змейка за горой
![2019-04-15 17_33_48-Hungry for apples - GameMaker Studio 2](https://user-images.githubusercontent.com/15930110/56132999-dbe4f000-5fa4-11e9-9304-ddd355ec6b9c.png)
![2019-04-15 17_33_56-Hungry for apples - GameMaker Studio 2](https://user-images.githubusercontent.com/15930110/56133000-dbe4f000-5fa4-11e9-9fe0-4f251c20f528.png)
![2019-04-15 17_34_26-Hungry for apples - GameMaker Studio 2](https://user-images.githubusercontent.com/15930110/56133001-dc7d8680-5fa4-11e9-8c42-571ad38ad89d.png)
![2019-04-15 17_34_37-Hungry for apples - GameMaker Studio 2](https://user-images.githubusercontent.com/15930110/56133007-de474a00-5fa4-11e9-81cd-9a700bad6689.png)

**Comment by oneza** [comment]
пофикшено
