### ISSUE TITLE
Яблоки спавняться только в левой части карты

### ISSUE THREAD

**Issue by m65v19** [oneza/RG#9]
Яблоки спавняться только в левой части карты(примерно до половины карты)
![2019-04-15 17_24_22-New Issue · oneza_RG](https://user-images.githubusercontent.com/15930110/56132481-83612300-5fa3-11e9-9d95-389bdd22dfbe.png)
![2019-04-15 17_24_30-New Issue · oneza_RG](https://user-images.githubusercontent.com/15930110/56132482-83612300-5fa3-11e9-94e2-ae0cbcd6983b.png)
![2019-04-15 17_24_41-New Issue · oneza_RG](https://user-images.githubusercontent.com/15930110/56132483-83612300-5fa3-11e9-843f-ad3dd75ce8f2.png)
![2019-04-15 17_24_49-New Issue · oneza_RG](https://user-images.githubusercontent.com/15930110/56132484-83612300-5fa3-11e9-88ca-4c9dc9867aee.png)
![2019-04-15 17_25_01-New Issue · oneza_RG](https://user-images.githubusercontent.com/15930110/56132485-83f9b980-5fa3-11e9-8026-54b72333e83f.png)
![2019-04-15 17_25_14-New Issue · oneza_RG](https://user-images.githubusercontent.com/15930110/56132486-83f9b980-5fa3-11e9-8e67-651af0260f21.png)

**Comment by oneza** [comment]
Пофикшено
